USE [master]
GO

CREATE DATABASE [ShoppingCart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShoppingCart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ShoppingCart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShoppingCart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\ShoppingCart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShoppingCart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShoppingCart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShoppingCart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShoppingCart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShoppingCart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShoppingCart] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShoppingCart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShoppingCart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShoppingCart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShoppingCart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShoppingCart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShoppingCart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShoppingCart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShoppingCart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShoppingCart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShoppingCart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ShoppingCart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShoppingCart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShoppingCart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShoppingCart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShoppingCart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShoppingCart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShoppingCart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShoppingCart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShoppingCart] SET  MULTI_USER 
GO

ALTER DATABASE [ShoppingCart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShoppingCart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShoppingCart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShoppingCart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShoppingCart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShoppingCart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShoppingCart] SET QUERY_STORE = ON
GO

ALTER DATABASE [ShoppingCart] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ShoppingCart] SET  READ_WRITE 
GO


USE [ShoppingCart]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Cart]') AND type in (N'U'))
DROP TABLE [dbo].[Cart]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cart](
	[CartId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL
) ON [PRIMARY]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CartItem]') AND type in (N'U'))
DROP TABLE [dbo].[CartItem]
GO

CREATE TABLE [dbo].[CartItem](
	[CartId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[ProductName] [varchar](200) NOT NULL,
	[ProductImagePath] [varchar](500) NOT NULL,
	[Price] [money] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_CartItem] PRIMARY KEY CLUSTERED 
(
	[CartId] ASC,
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


